# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lingwei/CLionProjects/spi_com

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lingwei/CLionProjects/spi_com

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lingwei/CLionProjects/spi_com/CMakeFiles /home/lingwei/CLionProjects/spi_com/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lingwei/CLionProjects/spi_com/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named spi_com

# Build rule for target.
spi_com: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spi_com
.PHONY : spi_com

# fast build rule for target.
spi_com/fast:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/build
.PHONY : spi_com/fast

#=============================================================================
# Target rules for targets named spi

# Build rule for target.
spi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spi
.PHONY : spi

# fast build rule for target.
spi/fast:
	$(MAKE) -f spi/CMakeFiles/spi.dir/build.make spi/CMakeFiles/spi.dir/build
.PHONY : spi/fast

#=============================================================================
# Target rules for targets named Sirius_Arm

# Build rule for target.
Sirius_Arm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sirius_Arm
.PHONY : Sirius_Arm

# fast build rule for target.
Sirius_Arm/fast:
	$(MAKE) -f Sirius_Arm/CMakeFiles/Sirius_Arm.dir/build.make Sirius_Arm/CMakeFiles/Sirius_Arm.dir/build
.PHONY : Sirius_Arm/fast

Sirius_Arm/Sirius_Arm.o: Sirius_Arm/Sirius_Arm.cpp.o

.PHONY : Sirius_Arm/Sirius_Arm.o

# target to build an object file
Sirius_Arm/Sirius_Arm.cpp.o:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/Sirius_Arm/Sirius_Arm.cpp.o
.PHONY : Sirius_Arm/Sirius_Arm.cpp.o

Sirius_Arm/Sirius_Arm.i: Sirius_Arm/Sirius_Arm.cpp.i

.PHONY : Sirius_Arm/Sirius_Arm.i

# target to preprocess a source file
Sirius_Arm/Sirius_Arm.cpp.i:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/Sirius_Arm/Sirius_Arm.cpp.i
.PHONY : Sirius_Arm/Sirius_Arm.cpp.i

Sirius_Arm/Sirius_Arm.s: Sirius_Arm/Sirius_Arm.cpp.s

.PHONY : Sirius_Arm/Sirius_Arm.s

# target to generate assembly for a file
Sirius_Arm/Sirius_Arm.cpp.s:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/Sirius_Arm/Sirius_Arm.cpp.s
.PHONY : Sirius_Arm/Sirius_Arm.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/main.cpp.s
.PHONY : main.cpp.s

spi/spi.o: spi/spi.cpp.o

.PHONY : spi/spi.o

# target to build an object file
spi/spi.cpp.o:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/spi/spi.cpp.o
.PHONY : spi/spi.cpp.o

spi/spi.i: spi/spi.cpp.i

.PHONY : spi/spi.i

# target to preprocess a source file
spi/spi.cpp.i:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/spi/spi.cpp.i
.PHONY : spi/spi.cpp.i

spi/spi.s: spi/spi.cpp.s

.PHONY : spi/spi.s

# target to generate assembly for a file
spi/spi.cpp.s:
	$(MAKE) -f CMakeFiles/spi_com.dir/build.make CMakeFiles/spi_com.dir/spi/spi.cpp.s
.PHONY : spi/spi.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... spi_com"
	@echo "... edit_cache"
	@echo "... spi"
	@echo "... Sirius_Arm"
	@echo "... Sirius_Arm/Sirius_Arm.o"
	@echo "... Sirius_Arm/Sirius_Arm.i"
	@echo "... Sirius_Arm/Sirius_Arm.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... spi/spi.o"
	@echo "... spi/spi.i"
	@echo "... spi/spi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

